name: Google Cloud Deploy

on:
  push:
    paths:
      - apps/api/**
    branches:
      - main

env:
  PROJECT_ID: liquid-folio-411711
  REGION: us-central1
  GAR_LOCATION: us-central1-docker.pkg.dev/liquid-folio-411711/test1
  IMAGE_NAME: api
  IMAGE_TAG: latest

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - id: "auth"
        uses: "google-github-actions/auth@v0.4.0"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0.2.1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: docker build . --file Dockerfile  --tag ${{ env.GAR_LOCATION }}${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Push image
        run: docker push ${{ env.GAR_LOCATION }}${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}